### ISSUE TITLE
/dn pay выдает ошибку

### ISSUE THREAD

**Issue by Wylabb** [PukPukov/qiwipay#1]
[latest.log](https://github.com/PukPukov/qiwipay/files/8594663/latest.log)
В общем ситуация такая, все настроил все сделал, но если пишу /dn pay то просто идет internal error, лог консоли прилагаю сверху

**Comment by Wylabb** [comment]
<img width="554" alt="Снимок экрана 2022-04-30 в 02 03 02" src="https://user-images.githubusercontent.com/77673282/166069109-f4eca1b2-2c76-45dc-9498-4539ab8742dc.png">
Прилагаю то как выглядит конфигурации

**Comment by PukPukov** [comment]
ошибка 401 - Unauthorized значит, что запрос не авторизирован. Судя по всему у тебя токен неправильный, и да, он неправильный, потому что p2p api даёт токены по длине раз в 5 больше, чем у тебя там введено

**Comment by PukPukov** [comment]
токены получать тут надо [p2p.qiwi.com](https://p2p.qiwi.com/)
